notifications:
  email:
    on_success: never
    on_failure: change

language: generic

os: linux
sudo: required
dist: trusty

before_install:
  - set -e;
  - sudo pip3 install --upgrade pip3
  - pip3 install conan --user
  - pip3 install bincrafters_remove_outdated
  - python --version
  - pip3 --version
  - conan --version

script:
  - conan remote add inexor https://api.bintray.com/conan/inexorgame/inexor-conan --insert
  - conan remote list
  - conan user -p "${CONAN_PASSWORD}" -r inexor "${CONAN_USER}"
  - bincrafters-remove-outdated inexor
