notifications:
  email:
    on_success: never
    on_failure: change

language: generic

os: linux
sudo: required
dist: trusty

before_install:
  - set -e;
  - sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1
  - sudo pip install --upgrade pip
  - pip install conan --user
  - pip install bincrafters_remove_outdated
  - python --version
  - pip --version
  - conan --version

script:
  - conan remote add inexor https://api.bintray.com/conan/inexorgame/inexor-conan --insert
  - conan remote list
  - conan user -p "${CONAN_PASSWORD}" -r inexor "${CONAN_USER}"
  - bincrafters-remove-outdated inexor
