sudo: required
dist: trusty
language: cpp

services:
  - docker

git:
  depth: 15

matrix:
  include:
# Our main compilers we run tests for
    - os: linux
      compiler: gcc
      env: os=linux docker_tag="optimization" TARGET=linux_gcc CONAN_COMPILER="gcc" CONAN_COMPILER_VERSION="6.3" CMAKE_CC="gcc-6" CMAKE_CXX="g++-6" NIGHTLY="conan"

    - os: linux
      compiler: clang
      env: os=linux docker_tag="optimization" TARGET=linux_clang CONAN_COMPILER="clang" CONAN_COMPILER_VERSION="4.0" CMAKE_CC="clang-4.0" CMAKE_CXX="clang++-4.0" NIGHTLY="conan"

# Older compilers we compile Conan packages for, to speed things up for other people
    - os: linux
      compiler: gcc
      env: os=linux docker_tag="legacy" TARGET=linux_gcc CONAN_COMPILER="gcc" CONAN_COMPILER_VERSION="5.4" CMAKE_CC="gcc-5" CMAKE_CXX="g++-5" NIGHTLY="conan"

    - os: linux
      compiler: clang
      env: os=linux docker_tag="legacy" TARGET=linux_clang CONAN_COMPILER="clang" CONAN_COMPILER_VERSION="3.9" CMAKE_CC="clang-3.9" CMAKE_CXX="clang++-3.9" NIGHTLY="conan"

    - os: linux
      compiler: clang
      env: os=linux docker_tag="legacy" TARGET=linux_clang CONAN_COMPILER="clang" CONAN_COMPILER_VERSION="3.8" CMAKE_CC="clang-3.8" CMAKE_CXX="clang++-3.8" NIGHTLY="conan"

    #- os: osx
      #sudo: false
      #osx_image: xcode8
      #compiler: clang
      #env: os=osx compiler=clang TARGET="osx" CMAKE_FLAGS="-DCMAKE_CXX_COMPILER=clang++-3.9 -DCMAKE_C_COMPILER=clang-3.9 -DBUILD_ALL=1"

  allow_failures:
    - env: os=linux docker_tag="legacy" TARGET=linux_gcc CONAN_COMPILER="gcc" CONAN_COMPILER_VERSION="5.4" CMAKE_CC="gcc-5" CMAKE_CXX="g++-5" NIGHTLY="conan"
    - env: os=linux docker_tag="optimization" TARGET=linux_clang CONAN_COMPILER="clang" CONAN_COMPILER_VERSION="4.0" CMAKE_CC="clang-4.0" CMAKE_CXX="clang++-4.0" NIGHTLY="conan"
    - env: os=linux docker_tag="legacy" TARGET=linux_clang CONAN_COMPILER="clang" CONAN_COMPILER_VERSION="3.8" CMAKE_CC="clang-3.8" CMAKE_CXX="clang++-3.8" NIGHTLY="conan"

  fast_finish: true # don't wait for allow_failures to fail, gives faster response
    #- os: linux
      #sudo: required
      #dist: trusty
      #env: TARGET=apidoc
      #git:
        #submodules: false

before_install:
  # Get our CI Docker image
  - if [ ${os} == 'linux' ]; then
    sudo docker pull inexorgame/ci-docker':'${docker_tag} ;
    fi

script:
  - if [ "$GLOBAL_NIGHTLY" == "false" ]; then
    NIGHTLY="false";
    fi
  - if [ "$GLOBAL_NIGHTLY" == "conan" ]; then
      NIGHTLY_USER="${CONAN_USER}";
      NIGHTLY_PASSWORD="${CONAN_PASSWORD}";
    else
      NIGHTLY_USER="${FTP_USER}";
      NIGHTLY_PASSWORD="${FTP_PASSWORD}";
    fi
  - if [ ${os} == 'linux' ]; then
    sudo docker run -v $(pwd)':'/inexor --net=host -it inexorgame/ci-docker':'${docker_tag} /inexor/inexor/tool/travis.sh target_script /inexor ${TARGET} ${CONAN_COMPILER} ${CONAN_COMPILER_VERSION} ${CMAKE_CC} ${CMAKE_CXX} ${TRAVIS_COMMIT} ${TRAVIS_BRANCH} ${TRAVIS_JOB_NUMBER} ${NIGHTLY} ${NIGHTLY_USER} ${NIGHTLY_PASSWORD} ${FTP_DOMAIN};
    fi

  - if [ ${os} == 'osx' ]; then
    bash tool/travis.sh target_before_install;
    fi
