version: 0.{build}
clone_depth: 1
clone_folder: C:\projects\inexor-game
# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true
# Maximum number of concurrent jobs for the project
max_jobs: 4

# https://www.appveyor.com/docs/build-environment/#build-worker-images
image: Visual Studio 2017

environment:
    # VS VERSION IN CMAKE STYLE
    matrix:
      - VSVERSION: "15 2017"
      - VSVERSION: "14 2015"

platform:
  - x64
  - Win32

configuration:
  - Release
  - Debug

# scripts that are called at very beginning, before repo cloning
init:
  - cmd: cmake --version
  - cmd: msbuild /version

# scripts that run after cloning repository
install:
  - appveyor-retry choco install doxygen.portable
  - cmd: python -m pip install conan
  - cmd: set "MAIN_FOLDER=C:\projects\inexor-game"
  - cmd: cd %MAIN_FOLDER%
  - cmd: git submodule update --init --recursive
  - cmd: set VSVERSIONSHORT=%VSVERSION:~0,2%


# scripts to run before build
before_build:
  # Fix detection of VS 2017 by e.g. OpenSSL
  - cmd: set "VS150COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\"
  - cmd: if "%VSVERSION%"=="15 2017" if "%platform%"=="x64" ( "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat" )
  - cmd: if "%VSVERSION%"=="15 2017" if "%platform%"=="Win32" ( "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsamd64_x86.bat" )

  - cmd: cd C:\projects\inexor-game\%RELATIVE_PATH%
  - cmd: md build
  - cmd: cd build

  # We generate project files for Visual Studio 14 2015 only atm.
  - cmd: if "%platform%"=="Win32" ( set "CMAKE_GENERATOR_NAME=Visual Studio %VSVERSION%" && set "arch_str=x86" )
  - cmd: if "%platform%"=="x64" ( set "CMAKE_GENERATOR_NAME=Visual Studio %VSVERSION% Win64" && set "arch_str=x86_64")
  - cmd: if %configuration%==Debug (set "runtime_str=MTd")else (set "runtime_str=MT")
  - cmd: set "args=-DBUILD_GLUEGEN=0 -DBUILD_CLIENT=1 -DBUILD_SERVER=1 -DBUILD_MASTER=1 -DBUILD_TEST=1 -DCREATE_PACKAGE=1"

  # Only deploy a bundle with the media folder if we actually want to have regular nightlies if the branch is master (and its not a pr)(and its a Release build):
  - cmd: if "%GLOBAL_NIGHTLY%"=="true" if "%configuration%"=="Release" if "%APPVEYOR_REPO_BRANCH%"=="master" if defined APPVEYOR_PULL_REQUEST_NUMBER set "args=%args% -DPACKAGE_INCLUDE_MEDIA=1"

  - cmd: if "%VSVERSION%"=="15 2017" ( conan install Boost/1.64.0@inexorgame/stable --scope build_all=1 --build=missing -s compiler="Visual Studio" -s compiler.version=%VSVERSIONSHORT% -s compiler.runtime=%runtime_str% -s arch=%arch_str% -s build_type=%configuration% )
  - cmd: if "%VSVERSION%"=="15 2017" ( conan install ENet/1.3.13@inexorgame/stable --scope build_all=1 --build=missing -s compiler="Visual Studio" -s compiler.version=%VSVERSIONSHORT% -s compiler.runtime=%runtime_str% -s arch=%arch_str% -s build_type=%configuration% )
  - cmd: if "%VSVERSION%"=="15 2017" ( conan install gRPC/1.1.0-dev@inexorgame/stable --scope build_all=1 --build=missing -s compiler="Visual Studio" -s compiler.version=%VSVERSIONSHORT% -s compiler.runtime=%runtime_str% -s arch=%arch_str% -s build_type=%configuration% )

  - cmd: if "%VSVERSION%"=="15 2017" if "%GLOBAL_NIGHTLY%"=="conan" ( conan user --password "%CONAN_PASSWORD%" "%CONAN_USER%" )
  - cmd: if "%VSVERSION%"=="15 2017" if "%GLOBAL_NIGHTLY%"=="conan" ( conan upload --all --confirm "*%CONAN_USER%*" )

  - cmd: conan install .. --scope build_all=1 --build=missing -s compiler="Visual Studio" -s compiler.version=%VSVERSIONSHORT% -s compiler.runtime=%runtime_str% -s arch=%arch_str% -s build_type=%configuration%
  - cmd: if "%GLOBAL_NIGHTLY%"=="conan" ( conan user --password "%CONAN_PASSWORD%" "%CONAN_USER%" )
  - cmd: if "%GLOBAL_NIGHTLY%"=="conan" ( conan upload --all --confirm "*%CONAN_USER%*" )
  - cmd: if "%GLOBAL_NIGHTLY%"=="true" ( cmake .. -G "%CMAKE_GENERATOR_NAME%" %args% -DCPACK_GENERATOR="NSIS;7Z" ) else ( cmake .. -G "%CMAKE_GENERATOR_NAME%" %args% )

build:
  project: C:\projects\inexor-game\%RELATIVE_PATH%build\PACKAGE.vcxproj
  # enable MSBuild parallel builds
  parallel: true

artifacts:
  # pushing a single file
  - path: build\Inexor-*.7z
  - path: build\Inexor-*.exe

deploy:
    # push our nightly bundle via ftp
 # - provider: FTP
 #   protocol: ftp
 #   host: inexor.org
 #   username:
 #     secure: rpQyxcVaaqNxDvYQlGP/eA==
 #   password:
 #     secure: aBNw6S6n1MqCfw/0S2vhDA==
    # push release binaries to GitHub if tag gets created (and create a release draft)
  - provider: GitHub
    auth_token:
      secure: vIfb9LX3nWCSRefUqY4JJL3hSosnPgKAbmGejFBL+C9GtHJKSuPLU6aMCrR79hPM
    draft: true
    prerelease: true
    on:
      # release from master branch only
      branch: master
      # deploy on tag push only
      appveyor_repo_tag: true
      configuration: release

test_script:
  - C:\projects\inexor-game\%RELATIVE_PATH%build\bin\unit_tests.exe
